// Popular accommodations constants
const POPULAR_ACCOMMODATIONS_REQUEST = 'POPULAR_ACCOMMODATIONS_REQUEST';
const POPULAR_ACCOMMODATIONS_RESULTS = 'POPULAR_ACCOMMODATIONS_RESULTS';
const POPULAR_ACCOMMODATIONS_RESULTS_RESET =
	'POPULAR_ACCOMMODATIONS_RESULTS_RESET';

// Search accommodations constants
const SEARCH_ACCOMMODATIONS_REQUEST = 'SEARCH_ACCOMMODATIONS_REQUEST';
const SEARCH_ACCOMMODATIONS_RESULTS = 'SEARCH_ACCOMMODATIONS_RESULTS';
const SEARCH_ACCOMMODATIONS_RESULTS_RESET =
	'SEARCH_ACCOMMODATIONS_RESULTS_RESET';
const SEARCH_ACCOMMODATIONS_USER_SELECTED =
	'SEARCH_ACCOMMODATIONS_USER_SELECTED';

export {
	POPULAR_ACCOMMODATIONS_REQUEST,
	POPULAR_ACCOMMODATIONS_RESULTS,
	POPULAR_ACCOMMODATIONS_RESULTS_RESET,
	SEARCH_ACCOMMODATIONS_REQUEST,
	SEARCH_ACCOMMODATIONS_RESULTS,
	SEARCH_ACCOMMODATIONS_USER_SELECTED,
	SEARCH_ACCOMMODATIONS_RESULTS_RESET,
};
